
services:
 pgvector:
  image: 'pgvector/pgvector:pg16'
  environment:
    - 'POSTGRES_DB=Rag_project'
    - 'POSTGRES_PASSWORD=postgres'
    - 'POSTGRES_USER=postpostgres'
  labels:
    - "org.springframework.boot.service-connection=postgres"
  ports:
    - '5432'
